version: 2
project_name: changelog-generator
before:
  hooks:
    - go mod download
    - go run ./internal/generate/completions --date={{ .CommitDate }}
    - go run ./internal/generate/manpages --version={{ .Version }} --date={{ .CommitDate }}
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{.CommitTimestamp}}"
archives:
  - formats: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md
      - manpages/*
      - completions/*
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-beta"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
  groups:
    - title: Features
      order: 0
      regexp: "(feat)"
    - title: Fixes
      order: 1
      regexp: "(fix|perf)"
    - title: Dependencies
      order: 999
      regexp: '\(deps\):'
    - title: Others
      order: 998
brews:
  - homepage: https://github.com/gabe565/changelog-generator
    description: Generates a changelog from commits since the previous release.
    license: MIT
    repository:
      owner: gabe565
      name: homebrew-tap
    directory: Formula
    install: |
      bin.install "changelog-generator"
      man1.install "manpages/changelog-generator.1.gz"
      bash_completion.install "completions/changelog-generator.bash" => "changelog-generator"
      zsh_completion.install "completions/changelog-generator.zsh" => "_changelog-generator"
      fish_completion.install "completions/changelog-generator.fish"
nfpms:
  - id: packages
    vendor: Gabe Cook
    homepage: https://github.com/gabe565/changelog-generator
    description: Generates a changelog from commits since the previous release.
    license: MIT
    maintainer: Gabe Cook <gabe565@gmail.com>
    formats:
      - deb
      - rpm
    contents:
      - src: ./manpages/
        dst: /usr/share/man/man1
        file_info:
          mode: 0644
      - src: ./completions/changelog-generator.bash
        dst: /usr/share/bash-completion/completions/changelog-generator
        file_info:
          mode: 0644
      - src: ./completions/changelog-generator.fish
        dst: /usr/share/fish/vendor_completions.d/changelog-generator.fish
        file_info:
          mode: 0644
      - src: ./completions/changelog-generator.zsh
        dst:  /usr/share/zsh/vendor-completions/_changelog-generator
        file_info:
          mode: 0644
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/gabe565/
aurs:
  - name: changelog-generator-bin
    homepage: https://github.com/gabe565/changelog-generator
    description: Generates a changelog from commits since the previous release.
    maintainers:
      - Gabe Cook <gabe565@gmail.com>
    license: MIT
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: ssh://aur@aur.archlinux.org/changelog-generator-bin.git
    skip_upload: auto
    package: |-
      # bin
      install -Dm755 "./changelog-generator" "${pkgdir}/usr/bin/changelog-generator"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/changelog-generator/LICENSE"
      # man pages
      install -Dm644 "./manpages/changelog-generator.1.gz" "${pkgdir}/usr/share/man/man1/changelog-generator.1.gz"
      # completions
      install -Dm644 "./completions/changelog-generator.bash" "${pkgdir}/usr/share/bash-completion/completions/changelog-generator"
      install -Dm644 "./completions/changelog-generator.zsh" "${pkgdir}/usr/share/zsh/site-functions/_changelog-generator"
      install -Dm644 "./completions/changelog-generator.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/changelog-generator.fish"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
