name: Test Action

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2022]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: ./
        id: changelog
        with:
          path: test
          install-only: "true"
      - name: Binary exists
        shell: bash
        run: command -v changelog-generator
      - name: Binary runs
        shell: bash
        run: changelog-generator --version
